CC = g++

# Para mais informações sobre as flags de warning, consulte a informação adicional no lab_ferramentas
CFLAGS = -std=c++11 -O3 -Wall -lm

all: p2

p2: p2.cpp
	$(CC) $(CFLAGS) -o p2 p2.cpp

clean:
	rm -f *.o p2