CC = g++

# Para mais informações sobre as flags de warning, consulte a informação adicional no lab_ferramentas
CFLAGS = -std=c++11 -O3 -Wall -lm

all: p1

p1: p1.cpp
	$(CC) $(CFLAGS) -o p1 p1.cpp

clean:
	rm -f *.o p1